import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.4";
import { decode as base64Decode } from "https://deno.land/std@0.168.0/encoding/base64.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const DEFAULT_STYLE = `STYLE: Hand-drawn sketch on beige/cream paper background. Pencil cross-hatching with slight roughness. Grayscale tones with ONLY blue (#4A90E2) as accent color for highlights and emphasis. Educational illustration style.`;
const TIMEOUT_MS = 55_000;
const PRIMARY_MODEL = "google/gemini-3-pro-image-preview";
const FALLBACK_MODEL = "google/gemini-3.1-flash-image-preview";

function extractBase64FromResponse(result: any): string | undefined {
  const message = result.choices?.[0]?.message;
  const images = message?.images;

  if (images && images.length > 0) {
    const imageDataUrl = images[0].image_url?.url || images[0];
    return typeof imageDataUrl === 'string' && imageDataUrl.includes(',')
      ? imageDataUrl.split(",")[1]
      : imageDataUrl;
  }

  if (message?.content && Array.isArray(message.content)) {
    const imagePart = message.content.find((p: any) => p.type === 'image_url' || p.type === 'image');
    if (imagePart) {
      const url = imagePart.image_url?.url || imagePart.url;
      return url?.includes(',') ? url.split(",")[1] : url;
    }
  }

  return undefined;
}

async function fetchAssetAsBase64(url: string): Promise<{ b64: string; contentType: string } | null> {
  try {
    const imgRes = await fetch(url);
    if (!imgRes.ok) { console.warn(`Failed to fetch asset image: ${url}`); return null; }
    const buf = await imgRes.arrayBuffer();
    const bytes = new Uint8Array(buf);
    let binary = '';
    for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
    const b64 = btoa(binary);
    const contentType = imgRes.headers.get('content-type') || 'image/png';
    console.log(`Asset image loaded: ${url.slice(-40)} (${bytes.length} bytes)`);
    return { b64, contentType };
  } catch (e) {
    console.warn(`Error fetching asset image ${url}:`, e);
    return null;
  }
}

async function callImageAIWithFallback(
  apiKey: string,
  contentParts: any[],
  panelCount?: number
): Promise<any> {
  const models = [PRIMARY_MODEL, FALLBACK_MODEL];

  for (let i = 0; i < models.length; i++) {
    const model = models[i];
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);

    try {
      console.log(`Trying image model: ${model}${panelCount ? ` (${panelCount} panels)` : ''}`);
      const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${apiKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model,
          messages: [{ role: "user", content: contentParts }],
          modalities: ["image", "text"],
        }),
        signal: controller.signal,
      });

      clearTimeout(timer);

      if (response.status === 429) throw { status: 429, message: "Rate limited — please try again in a moment" };
      if (response.status === 402) throw { status: 402, message: "AI credits exhausted — please add funds in Settings > Workspace > Usage" };
      if (!response.ok) {
        const errText = await response.text();
        throw new Error(`AI Gateway error [${response.status}]: ${errText}`);
      }

      const result = await response.json();
      const base64Data = extractBase64FromResponse(result);
      if (!base64Data) {
        console.error("No image in response:", JSON.stringify(result).slice(0, 2000));
        throw new Error("No image generated by model");
      }

      return base64Data;
    } catch (e: any) {
      clearTimeout(timer);
      if (e?.status === 429 || e?.status === 402) throw e;
      if (i === models.length - 1) throw e;
      console.warn(`Model ${model} failed, trying fallback:`, e.message || e);
    }
  }
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { imagePrompt, projectId, segmentId, sequenceNumber, subIndex, momentType, stylePrefix, assetDescriptions, assetImageUrls, panelCount, panelPrompts } = await req.json();
    if (!imagePrompt || !projectId) throw new Error("imagePrompt and projectId required");

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY not configured");

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    const activeStyle = stylePrefix || DEFAULT_STYLE;

    // Build asset reference instruction
    let assetBlock = '';
    if (assetDescriptions && Array.isArray(assetDescriptions) && assetDescriptions.length > 0) {
      const assetLines = assetDescriptions.map(
        (a: { name: string; description: string; category?: string }) =>
          `- ${a.name}: ${a.description}`
      ).join('\n');
      assetBlock = `\nVISUAL REFERENCES:\n${assetLines}\nIMPORTANT: Draw them exactly like the reference images provided — maintaining the same face, hair, and clothing style. But not every scene needs to include them — only when it makes visual sense for the content.\n`;
    }

    // Build the text prompt — support panel mode
    let textPrompt: string;
    const isPanelMode = panelCount && panelCount > 1 && panelPrompts && Array.isArray(panelPrompts);

    if (isPanelMode) {
      const panelDescriptions = panelPrompts.map((p: string, i: number) => `PANEL ${i + 1}: ${p}`).join('\n');
      textPrompt = `ABSOLUTE REQUIREMENT: Create a SINGLE image with ${panelCount} panels stacked VERTICALLY.
Each panel has aspect ratio 16:9. Separate panels with a thin white horizontal line (4px).
The final image should be ${1920}x${1080 * panelCount} pixels total.

CRITICAL LANGUAGE RULE: ALL visible text in the image MUST be in Brazilian Portuguese (PT-BR). NEVER use English text.
ANTI-NARRATION TEXT RULE: NEVER transcribe full narration sentences into the image. Maximum 1-4 visible words per panel (titles, labels, numeric values only).
ACRONYM RULE: Use correct abbreviated form of acronyms, never spell them phonetically.
COMPOSITION RULE: Main element centered occupying 60-70% of each panel frame.
${activeStyle}
NEVER include brand names, channel names, or logos.
${assetBlock}

${panelDescriptions}`;
    } else {
      textPrompt = `ABSOLUTE REQUIREMENT: Aspect ratio 16:9 (1920x1080 widescreen).
CRITICAL LANGUAGE RULE: ALL visible text in the image MUST be in Brazilian Portuguese (PT-BR). NEVER use English text.
ANTI-NARRATION TEXT RULE: NEVER transcribe full narration sentences into the image. Maximum 1-4 visible words (titles, labels, numeric values only).
ACRONYM RULE: Use correct abbreviated form of acronyms, never spell them phonetically.
COMPOSITION RULE: Main element centered occupying 60-70% of the frame. Supporting context at the edges.
${activeStyle}
NEVER include brand names, channel names, or logos.
${assetBlock}
Scene: ${imagePrompt}`;
    }

    // Build multimodal content parts
    const contentParts: any[] = [{ type: "text", text: textPrompt }];

    // Fetch asset images as base64 inline data
    if (assetImageUrls && Array.isArray(assetImageUrls)) {
      const urls = assetImageUrls.filter((u: unknown) => u && typeof u === 'string').slice(0, 5);
      for (const url of urls) {
        const result = await fetchAssetAsBase64(url as string);
        if (result) {
          contentParts.push({
            type: "image_url",
            image_url: { url: `data:${result.contentType};base64,${result.b64}` },
          });
        }
      }
    }

    // Call AI with fallback
    const base64Data = await callImageAIWithFallback(LOVABLE_API_KEY, contentParts, isPanelMode ? panelCount : undefined);

    const imageBytes = base64Decode(base64Data);
    const num = String(sequenceNumber).padStart(3, "0");
    const subSuffix = subIndex ? `-sub-${subIndex}` : "";
    const panelSuffix = isPanelMode ? "-panels" : "";
    const fileName = `${projectId}/segment-${num}${subSuffix}${panelSuffix}.png`;

    const { error: uploadErr } = await supabase.storage
      .from("segment-images")
      .upload(fileName, imageBytes, { upsert: true, contentType: "image/png" });
    if (uploadErr) throw uploadErr;

    const { data: urlData } = supabase.storage.from("segment-images").getPublicUrl(fileName);

    return new Response(JSON.stringify({
      imageUrl: urlData.publicUrl + `?t=${Date.now()}`,
      isPanelImage: !!isPanelMode,
      panelCount: isPanelMode ? panelCount : 1,
    }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e: any) {
    console.error("generate-image error:", e);
    const status = e?.status || 500;
    const message = e?.message || (e instanceof Error ? e.message : "Unknown error");
    return new Response(JSON.stringify({ error: message }), {
      status,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
